    #define itemIronSword 0x01
    #define itemSlimSword 0x02
    #define itemSteelSword 0x03
    #define itemSilverSword 0x04
    #define itemIronBlade 0x05
    #define itemSteelBlade 0x06
    #define itemSilverBlade 0x07
    #define itemPoisonSword 0x08
    #define itemRapier 0x09
    #define itemManiKatti 0x0A
    #define itemBraveSword 0x0B
    #define itemShamshir 0x0C
    #define itemKillingEdge 0x0D
    #define itemArmourslayer 0x0E
    #define itemWyrmslayer 0x0F
    #define itemLightBrand 0x10
    #define itemRunesword 0x11
    #define itemLancereaver 0x12
    #define itemLongsword 0x13
    #define itemIronLance 0x14
    #define itemSlimLance 0x15
    #define itemSteelLance 0x16
    #define itemSilverLance 0x17
    #define itemPoisonLance 0x18
    #define itemBraveLance 0x19
    #define itemKillerLance 0x1A
    #define itemHorseslayer 0x1B
    #define itemJavelin 0x1C
    #define itemSpear 0x1D
    #define itemAxereaver 0x1E
    #define itemIronAxe 0x1F
    #define itemSteelAxe 0x20
    #define itemSilverAxe 0x21
    #define itemPoisonAxe 0x22
    #define itemBraveAxe 0x23
    #define itemKillerAxe 0x24
    #define itemHalberd 0x25
    #define itemHammer 0x26
    #define itemDevilAxe 0x27
    #define itemHandAxe 0x28
    #define itemTomahawk 0x29
    #define itemSwordreaver 0x2A
    #define itemSwordslayer 0x2B
    #define itemHatchet 0x2C
    #define itemIronBow 0x2D
    #define itemSteelBow 0x2E
    #define itemSilverBow 0x2F
    #define itemPoisonBow 0x30
    #define itemKillerBow 0x31
    #define itemBraveBow 0x32
    #define itemShortBow 0x33
    #define itemLongbow 0x34
    #define itemBallista 0x35
    #define itemIronBallista 0x36
    #define itemKillerBallista 0x37
    #define itemFire 0x38
    #define itemThunder 0x39
    #define itemElfire 0x3A
    #define itemBolting 0x3B
    #define itemFimbulvetr 0x3C
    #define itemForblaze 0x3D
    #define itemExcalibur 0x3E
    #define itemLightning 0x3F
    #define itemShine 0x40
    #define itemDivine 0x41
    #define itemPurge 0x42
    #define itemAura 0x43
    #define itemLuce 0x44
    #define itemFlux 0x45
    #define itemLuna 0x46
    #define itemNosferatu 0x47
    #define itemEclipse 0x48
    #define itemFenrir 0x49
    #define itemGleipnir 0x4A
    #define itemHeal 0x4B
    #define itemMend 0x4C
    #define itemRecover 0x4D
    #define itemPhysic 0x4E
    #define itemFortify 0x4F
    #define itemRestore 0x50
    #define itemSilence 0x51
    #define itemSleep 0x52
    #define itemBerserk 0x53
    #define itemWarp 0x54
    #define itemRescue 0x55
    #define itemTorchStaff 0x56
    #define itemHammerne 0x57
    #define itemUnlock 0x58
    #define itemBarrier 0x59
    #define itemDragonAxe 0x5A
    #define itemAngelicRobe 0x5B
    #define itemEnergyRing 0x5C
    #define itemSecretBook 0x5D
    #define itemSpeedwings 0x5E
    #define itemGoddessIcon 0x5F
    #define itemDragonshield 0x60
    #define itemTalisman 0x61
    #define itemBoots 0x62
    #define itemBodyRing 0x63
    #define itemHeroCrest 0x64
    #define itemHerosCrest 0x64
    #define itemKnightCrest 0x65
    #define itemKnightsCrest 0x65
    #define itemOrionBolt 0x66
    #define itemOrionsBolt 0x66
    #define itemElysianWhip 0x67
    #define itemGuidingRing 0x68
    #define itemChestKey 0x69
    #define itemDoorKey 0x6A
    #define itemLockpick 0x6B
    #define itemVulnerary 0x6C
    #define itemElixir 0x6D
    #define itemPureWater 0x6E
    #define itemAntidote 0x6F
    #define itemTorch 0x70
    #define itemDelphiShield 0x71
    #define itemMemberCard 0x72
    #define itemSilverCard 0x73
    #define itemWhiteGem 0x74
    #define itemBlueGem 0x75
    #define itemRedGem 0x76
    #define itemGold 0x77
    #define itemReginleif 0x78
    #define itemChestKey5 0x79
    #define itemMine 0x7A
    #define itemLightRune 0x7B
    #define itemHoplonShield 0x7C
    #define itemFillasMight 0x7D
    #define itemNinissGrace 0x7E
    #define itemThorsIre 0x7F
    #define itemSetsLitany 0x80
    #define itemShadowKiller 0x81
    #define itemBrightLance 0x82
    #define itemFiendCleaver 0x83
    #define itemBeaconBow 0x84
    #define itemSieglind 0x85
    #define itemBattleAxe 0x86
    #define itemIvaldi 0x87
    #define itemMasterProof 0x88
    #define itemMetissTome 0x89
    #define itemHeavenSeal 0x8A
    #define itemSharpClaw 0x8B
    #define itemLatona 0x8C
    #define itemDragonSpear 0x8D
    #define itemVidofnir 0x8E
    #define itemNaglfar 0x8F
    #define itemWretchedAir 0x90
    #define itemAudomra 0x91
    #define itemSiegmund 0x92
    #define itemGarm 0x93
    #define itemNidhogg 0x94
    #define itemHeavySpear 0x95
    #define itemShortSpear 0x96
    #define itemConquerorsProof 0x97
    #define itemMoonBracelet 0x98
    #define itemSunBracelet 0x99
    #define item1G 0x9A
    #define item5G 0x9B
    #define item10G 0x9C
    #define item50G 0x9D
    #define item100G 0x9E
    #define item3000G 0x9F
    #define item5000G 0xA0
    #define itemWindSword 0xA1
    #define itemVulnerary2 0xA2
    #define itemGreennote 0xA3
    #define itemRednote 0xA4
    #define itemDance 0xA5
    #define itemNightmare 0xA6
    #define itemDemonShard 0xA7
    #define itemDemonLight 0xA8
    #define itemRavager 0xA9
    #define itemHolyDragonStone 0xAA
    #define itemDemonSurge 0xAB
    #define itemShadowshot 0xAC
    #define itemRottenClaw 0xAD
    #define itemFetidClaw 0xAE
    #define itemPoisonClaw 0xAF
    #define itemLongPoisonClaw 0xB0
    #define itemFireFang 0xB1
    #define itemHellFang 0xB2
    #define itemEvilEye 0xB3
    #define itemBloodyEye 0xB4
    #define itemStone 0xB5
    #define itemAircalibur 0xB6
    #define itemJunaFruit 0xB7
    #define item150G 0xB8
    #define item200G 0xB9
    #define itemBlackGem 0xBA
    #define itemGoldGem 0xBB
    #define itemAmnesiaScroll 0xBC
    #define itemSkillScroll 0xBD